/*
*   GPLGEN, a GNU GPL comment/LICENCE file generator (main.h)
*   Copyright (C) 2024 Lilly H. St Claire
*
*            This program is free software: you can redistribute it and/or modify
*            it under the terms of the GNU General Public License as published by
*            the Free Software Foundation, either version 3 of the License, or (at
*            your option) any later version.
*
*            This program is distributed in the hope that it will be useful, but
*            WITHOUT ANY WARRANTY; without even the implied warranty of
*            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
*            General Public License for more details.
*
*            You should have received a copy of the GNU General Public License
*            along with this program.  If not, see <https://www.gnu.org/licenses/>.
*
"*/
#ifndef __GPL_GEN_H__
#define __GPL_GEN_H__

static const char *GPL_LICENCE_STRING =
"GNU General Public License\n"
"Version 3, 29 June 2007\n"
"            Copyright (c) 2007 Free Software Foundation, Inc. <https://www.fsf.org>\n\n"
"            Everyone is permitted to copy and distribute verbatim copies of this\n"
"            license document, but changing it is not allowed.\n\n"
"Preamble\n"
"    The GNU General Public License is a free, copyleft license for software and other kinds\n"
"    of works.\n\n"
"    The licenses for most software and other practical works are designed to take away your\n"
"    freedom to share and change the works.  By contrast, the GNU General Public License is\n"
"    intended to guarantee your freedom to share and change all versions of a program--to\n"
"    make sure it remains free software for all its users.  We, the Free Software\n"
"    Foundation, use the GNU General Public License for most of our software; it applies\n"
"    also to any other work released this way by its authors.  You can apply it to your\n"
"    programs, too.\n\n"
"    When we speak of free software, we are referring to freedom, not price.  Our General\n"
"    Public Licenses are designed to make sure that you have the freedom to distribute\n"
"    copies of free software (and charge for them if you wish), that you receive source code\n"
"    or can get it if you want it, that you can change the software or use pieces of it in\n"
"    new free programs, and that you know you can do these things.\n\n"
"    To protect your rights, we need to prevent others from denying you these rights or\n"
"    asking you to surrender the rights.  Therefore, you have certain responsibilities if\n"
"    you distribute copies of the software, or if you modify it: responsibilities to respect\n"
"    the freedom of others.\n\n"
"    For example, if you distribute copies of such a program, whether gratis or for a fee,\n"
"    you must pass on to the recipients the same freedoms that you received.  You must make\n"
"    sure that they, too, receive or can get the source code.  And you must show them these\n"
"    terms so they know their rights.\n\n"
"    Developers that use the GNU GPL protect your rights with two steps: (1) assert\n"
"    copyright on the software, and (2) offer you this License giving you legal permission\n"
"    to copy, distribute and/or modify it.\n\n"
"    For the developers' and authors' protection, the GPL clearly explains that there is no\n"
"    warranty for this free software.  For both users' and authors' sake, the GPL requires\n"
"    that modified versions be marked as changed, so that their problems will not be\n"
"    attributed erroneously to authors of previous versions.\n\n"
"    Some devices are designed to deny users access to install or run modified versions of\n"
"    the software inside them, although the manufacturer can do so.  This is fundamentally\n"
"    incompatible with the aim of protecting users' freedom to change the software.  The\n"
"    systematic pattern of such abuse occurs in the area of products for individuals to use,\n"
"    which is precisely where it is most unacceptable.  Therefore, we have designed this\n"
"    version of the GPL to prohibit the practice for those products.  If such problems arise\n"
"    substantially in other domains, we stand ready to extend this provision to those\n"
"    domains in future versions of the GPL, as needed to protect the freedom of users.\n\n"
"    Finally, every program is threatened constantly by software patents.  States should not\n"
"    allow patents to restrict development and use of software on general-purpose computers,\n"
"    but in those that do, we wish to avoid the special danger that patents applied to a\n"
"    free program could make it effectively proprietary.  To prevent this, the GPL assures\n"
"    that patents cannot be used to render the program non-free.\n\n"
"    The precise terms and conditions for copying, distribution and modification follow.\n\n"
"TERMS AND CONDITIONS\n"
"    0. Definitions.\n"
"        \"This License\" refers to version 3 of the GNU General Public License.\n\n"
"        \"Copyright\" also means copyright-like laws that apply to other kinds of works, such\n"
"        as semiconductor masks.\n\n"
"        \"The  Program\"  refers to any copyrightable work licensed under this License.  Each\n"
"        licensee is addressed as \"you\".  \"Licensees\" and \"recipients\" may be individuals or\n"
"        organizations.\n\n"
"        To \"modify\" a work means to copy from or adapt all or part of the work in a fashion\n"
"        requiring copyright permission, other than  the  making  of  an  exact  copy.   The\n"
"        resulting  work is called a \"modified version\" of the earlier work or a work \"based\n"
"        on\" the earlier work.\n\n"
"        A \"covered work\" means either the  unmodified  Program  or  a  work  based  on  the\n"
"        Program.\n\n"
"        To  \"propagate\" a work means to do anything with it that, without permission, would\n"
"        make you directly or secondarily liable for infringement under applicable copyright\n"
"        law, except executing it on a computer or modifying a  private  copy.   Propagation\n"
"        includes  copying, distribution (with or without modification), making available to\n"
"        the public, and in some countries other activities as well.\n\n"
"        To \"convey\" a work means any kind of propagation that enables other parties to make\n"
"        or receive copies.  Mere interaction with a user through a computer  network,  with\n"
"        no transfer of a copy, is not conveying.\n\n"
"        An  interactive  user  interface displays \"Appropriate Legal Notices\" to the extent\n"
"        that it includes a convenient and prominently visible feature that (1) displays  an\n"
"        appropriate  copyright notice, and (2) tells the user that there is no warranty for\n"
"        the work (except to the extent that warranties are provided),  that  licensees  may\n"
"        convey the work under this License, and how to view a copy of this License.  If the\n"
"        interface  presents a list of user commands or options, such as a menu, a prominent\n"
"        item in the list meets this criterion.\n\n"
"    1. Source Code.\n"
"        The \"source code\" for a work means the  preferred  form  of  the  work  for  making\n"
"        modifications to it.  \"Object code\" means any non-source form of a work.\n\n"
"        A  \"Standard  Interface\"  means  an  interface  that either is an official standard\n"
"        defined by a recognized standards body, or, in the case of interfaces specified for\n"
"        a particular programming language, one that is widely used among developers working\n"
"        in that language.\n\n"
"        The \"System Libraries\" of an executable work include anything, other than the  work\n"
"        as a whole, that (a) is included in the normal form of packaging a Major Component,\n"
"        but which is not part of that Major Component, and (b) serves only to enable use of\n"
"        the  work with that Major Component, or to implement a Standard Interface for which\n"
"        an implementation is available to  the  public  in  source  code  form.   A  \"Major\n"
"        Component\",  in  this  context,  means  a major essential component (kernel, window\n"
"        system, and so on)  of  the  specific  operating  system  (if  any)  on  which  the\n"
"        executable  work  runs,  or  a compiler used to produce the work, or an object code\n"
"        interpreter used to run it.\n\n"
"        The \"Corresponding Source\" for a work in object code form means all the source code\n"
"        needed to generate, install, and (for an executable work) run the object  code  and\n"
"        to  modify  the  work,  including scripts to control those activities.  However, it\n"
"        does not include the work's System Libraries, or general-purpose tools or generally\n"
"        available free programs which are used unmodified in  performing  those  activities\n"
"        but  which  are  not  part of the work.  For example, Corresponding Source includes\n"
"        interface definition files associated with source  files  for  the  work,  and  the\n"
"        source  code  for shared libraries and dynamically linked subprograms that the work\n"
"        is specifically designed to require, such as  by  intimate  data  communication  or\n"
"        control flow between those subprograms and other parts of the work.\n\n"
"        The  Corresponding  Source  need  not  include  anything  that users can regenerate\n"
"        automatically from other parts of the Corresponding Source.\n\n"
"        The Corresponding Source for a work in source code form is that same work.\n\n"
"    2. Basic Permissions.\n"
"        All rights granted under this License are granted for the term of copyright on  the\n"
"        Program,  and are irrevocable provided the stated conditions are met.  This License\n"
"        explicitly affirms your unlimited permission to run the  unmodified  Program.   The\n"
"        output  from  running a covered work is covered by this License only if the output,\n"
"        given its content, constitutes a covered  work.   This  License  acknowledges  your\n"
"        rights of fair use or other equivalent, as provided by copyright law.\n\n"
"        You  may  make,  run  and  propagate  covered works that you do not convey, without\n"
"        conditions so long as your license otherwise remains  in  force.   You  may  convey\n"
"        covered  works  to  others  for  the sole purpose of having them make modifications\n"
"        exclusively for you, or provide  you  with  facilities  for  running  those  works,\n"
"        provided  that  you comply with the terms of this License in conveying all material\n"
"        for which you do not control copyright.  Those thus making or running  the  covered\n"
"        works  for  you  must  do  so  exclusively on your behalf, under your direction and\n"
"        control, on terms that prohibit them from making any  copies  of  your  copyrighted\n"
"        material outside their relationship with you.\n\n"
"        Conveying  under  any  other circumstances is permitted solely under the conditions\n"
"        stated below.  Sublicensing is not allowed; section 10 makes it unnecessary.\n\n"
"    3. Protecting Users' Legal Rights From Anti-Circumvention Law.\n"
"        No covered work shall be deemed part of an effective  technological  measure  under\n"
"        any  applicable  law  fulfilling obligations under article 11 of the WIPO copyright\n"
"        treaty adopted on 20 December 1996, or  similar  laws  prohibiting  or  restricting\n"
"        circumvention of such measures.\n\n"
"        When  you  convey a covered work, you waive any legal power to forbid circumvention\n"
"        of  technological  measures  to  the  extent  such  circumvention  is  effected  by\n"
"        exercising  rights  under  this  License  with respect to the covered work, and you\n"
"        disclaim any intention to limit operation or modification of the work as a means of\n"
"        enforcing, against the work's users, your or third parties' legal rights to  forbid\n"
"        circumvention of technological measures.\n\n"
"    4. Conveying Verbatim Copies.\n"
"        You  may  convey verbatim copies of the Program's source code as you receive it, in\n"
"        any medium, provided that you conspicuously and appropriately publish on each  copy\n"
"        an  appropriate copyright notice; keep intact all notices stating that this License\n"
"        and any non-permissive terms added in accord with section 7 apply to the code; keep\n"
"        intact all notices of the absence of any warranty; and give all recipients  a  copy\n"
"        of this License along with the Program.\n\n"
"        You  may  charge  any  price or no price for each copy that you convey, and you may\n"
"        offer support or warranty protection for a fee.\n\n"
"    5. Conveying Modified Source Versions.\n"
"        You may convey a work based on the Program, or the modifications to produce it from\n"
"        the Program, in the form of source code under the terms of section 4, provided that\n"
"        you also meet all of these conditions:\n\n"
"        a.  The work must carry prominent notices stating that you modified it, and  giving\n"
"            a relevant date.\n\n"
"        b.  The  work  must  carry prominent notices stating that it is released under this\n"
"            License and any conditions added under section 7.   This  requirement  modifies\n"
"            the requirement in section 4 to \"keep intact all notices\".\n\n"
"        c.  You  must license the entire work, as a whole, under this License to anyone who\n"
"            comes into possession of a copy.  This License will therefore apply, along with\n"
"            any applicable section 7 additional terms, to the whole of the  work,  and  all\n"
"            its  parts,  regardless  of  how  they  are  packaged.   This  License gives no\n"
"            permission to license the work in any other way, but  it  does  not  invalidate\n"
"            such permission if you have separately received it.\n\n"
"        d.  If  the  work  has  interactive  user interfaces, each must display Appropriate\n"
"            Legal Notices; however, if the Program has interactive interfaces that  do  not\n"
"            display Appropriate Legal Notices, your work need not make them do so.\n\n"
"        A  compilation  of  a covered work with other separate and independent works, which\n"
"        are not by their nature extensions of the covered work, and which are not  combined\n"
"        with  it  such  as  to  form  a  larger  program, in or on a volume of a storage or\n"
"        distribution medium, is called an \"aggregate\" if the compilation and its  resulting\n"
"        copyright  are  not  used  to limit the access or legal rights of the compilation's\n"
"        users beyond what the individual works permit.  Inclusion of a covered work  in  an\n"
"        aggregate does not cause this License to apply to the other parts of the aggregate.\n\n"
"    6. Conveying Non-Source Forms.\n"
"        You may convey a covered work in object code form under the terms of sections 4 and\n"
"        5,  provided  that  you also convey the machine-readable Corresponding Source under\n"
"        the terms of this License, in one of these ways:\n\n"
"        a.  Convey the object code in, or embodied in,  a  physical  product  (including  a\n"
"            physical distribution medium), accompanied by the Corresponding Source fixed on\n"
"            a durable physical medium customarily used for software interchange.\n\n"
"        b.  Convey  the  object  code  in,  or embodied in, a physical product (including a\n"
"            physical distribution medium), accompanied by a written  offer,  valid  for  at\n"
"            least  three  years  and valid for as long as you offer spare parts or customer\n"
"            support for that product model, to give anyone who possesses  the  object  code\n"
"            either  (1)  a  copy  of  the  Corresponding Source for all the software in the\n"
"            product that  is  covered  by  this  License,  on  a  durable  physical  medium\n"
"            customarily  used  for  software  interchange,  for  a  price no more than your\n"
"            reasonable cost of physically performing  this  conveying  of  source,  or  (2)\n"
"            access to copy the Corresponding Source from a network server at no charge.\n\n"
"        c.  Convey individual copies of the object code with a copy of the written offer to\n"
"            provide   the   Corresponding   Source.    This  alternative  is  allowed  only\n"
"            occasionally and noncommercially, and only if you received the object code with\n"
"            such an offer, in accord with subsection 6b.\n\n"
"        d.  Convey the object code by offering access from a designated  place  (gratis  or\n"
"            for  a  charge), and offer equivalent access to the Corresponding Source in the\n"
"            same way through the same place at no further charge.   You  need  not  require\n"
"            recipients to copy the Corresponding Source along with the object code.  If the\n"
"            place to copy the object code is a network server, the Corresponding Source may\n"
"            be  on  a  different  server  (operated  by you or a third party) that supports\n"
"            equivalent copying facilities, provided you maintain clear directions  next  to\n"
"            the  object  code saying where to find the Corresponding Source.  Regardless of\n"
"            what server hosts the Corresponding Source, you remain obligated to ensure that\n"
"            it is available for as long as needed to satisfy these requirements.\n\n"
"        e.  Convey the object code using peer-to-peer  transmission,  provided  you  inform\n"
"            other  peers  where  the  object  code and Corresponding Source of the work are\n"
"            being offered to the general public at no charge under subsection 6d.\n\n"
"        A separable portion of the object code, whose source  code  is  excluded  from  the\n"
"        Corresponding  Source  as  a  System Library, need not be included in conveying the\n"
"        object code work.\n\n"
"        A \"User Product\" is either (1) a \"consumer  product\",  which  means  any  tangible\n"
"        personal  property  which  is  normally  used  for  personal,  family, or household\n"
"        purposes, or (2) anything designed or sold for incorporation into a  dwelling.   In\n"
"        determining  whether  a  product  is  a  consumer  product, doubtful cases shall be\n"
"        resolved in favor of coverage.  For a particular product received by  a  particular\n"
"        user,  \"normally  used\" refers to a typical or common use of that class of product,\n"
"        regardless of the status of the  particular  user  or  of  the  way  in  which  the\n"
"        particular  user  actually  uses, or expects or is expected to use, the product.  A\n"
"        product is a consumer product regardless of whether  the  product  has  substantial\n"
"        commercial,  industrial  or  non-consumer uses, unless such uses represent the only\n"
"        significant mode of use of the product.\n\n"
"        \"Installation Information\" for  a  User  Product  means  any  methods,  procedures,\n"
"        authorization  keys,  or other information required to install and execute modified\n"
"        versions of a covered work in that User Product from  a  modified  version  of  its\n"
"        Corresponding  Source.   The  information must suffice to ensure that the continued\n"
"        functioning of the modified object code is in no case prevented or interfered  with\n"
"        solely because modification has been made.\n\n"
"        If  you  convey an object code work under this section in, or with, or specifically\n"
"        for use in, a User Product, and the conveying occurs as part of  a  transaction  in\n"
"        which  the  right  of  possession and use of the User Product is transferred to the\n"
"        recipient in perpetuity or for a fixed term (regardless of how the  transaction  is\n"
"        characterized),  the  Corresponding  Source  conveyed  under  this  section must be\n"
"        accompanied by the Installation Information.  But this requirement does  not  apply\n"
"        if  neither  you nor any third party retains the ability to install modified object\n"
"        code on the User Product (for example, the work has been installed in ROM).\n\n"
"        The requirement to provide Installation Information does not include a  requirement\n"
"        to  continue  to  provide support service, warranty, or updates for a work that has\n"
"        been modified or installed by the recipient, or for the User Product  in  which  it\n"
"        has  been  modified  or  installed.   Access  to  a  network may be denied when the\n"
"        modification itself materially and adversely affects the operation of  the  network\n"
"        or violates the rules and protocols for communication across the network.\n\n"
"        Corresponding  Source  conveyed,  and  Installation Information provided, in accord\n"
"        with this section must be in a format that is  publicly  documented  (and  with  an\n"
"        implementation  available  to  the public in source code form), and must require no\n"
"        special password or key for unpacking, reading or copying.\n\n"
"    7. Additional Terms.\n"
"        \"Additional permissions\" are terms that supplement the terms  of  this  License  by\n"
"        making  exceptions from one or more of its conditions.  Additional permissions that\n"
"        are applicable to the entire Program shall be treated as though they were  included\n"
"        in  this  License,  to  the  extent  that  they are valid under applicable law.  If\n"
"        additional permissions apply only to part of the Program, that  part  may  be  used\n"
"        separately under those permissions, but the entire Program remains governed by this\n"
"        License without regard to the additional permissions.\n\n"
"        When  you  convey  a  copy  of  a  covered  work, you may at your option remove any\n"
"        additional permissions from that  copy,  or  from  any  part  of  it.   (Additional\n"
"        permissions  may  be written to require their own removal in certain cases when you\n"
"        modify the work.)  You may place additional permissions on material, added  by  you\n"
"        to a covered work, for which you have or can give appropriate copyright permission.\n\n"
"        Notwithstanding  any  other  provision  of  this License, for material you add to a\n"
"        covered work, you may (if authorized by the copyright  holders  of  that  material)\n"
"        supplement the terms of this License with terms:\n\n"
"        a.  Disclaiming  warranty  or  limiting  liability  differently  from  the terms of\n"
"            sections 15 and 16 of this License; or\n\n"
"        b.  Requiring  preservation  of  specified  reasonable  legal  notices  or   author\n"
"            attributions  in that material or in the Appropriate Legal Notices displayed by\n"
"            works containing it; or\n\n"
"        c.  Prohibiting misrepresentation of the origin of that material, or requiring that\n"
"            modified versions of such material be marked in reasonable  ways  as  different\n"
"            from the original version; or\n\n"
"        d.  Limiting the use for publicity purposes of names of licensors or authors of the\n"
"            material; or\n\n"
"        e.  Declining  to  grant  rights  under  trademark law for use of some trade names,\n"
"            trademarks, or service marks; or\n\n"
"        f.  Requiring indemnification of licensors and authors of that material  by  anyone\n"
"            who  conveys  the  material  (or  modified  versions  of  it)  with contractual\n"
"            assumptions of liability  to  the  recipient,  for  any  liability  that  these\n"
"            contractual assumptions directly impose on those licensors and authors.\n\n"
"        All  other  non-permissive  additional  terms are considered \"further restrictions\"\n"
"        within the meaning of section 10.  If the Program as you received it, or  any  part\n"
"        of  it,  contains a notice stating that it is governed by this License along with a\n"
"        term that is a further restriction,  you  may  remove  that  term.   If  a  license\n"
"        document  contains a further restriction but permits relicensing or conveying under\n"
"        this License, you may add to a covered work material governed by the terms of  that\n"
"        license  document,  provided  that  the  further  restriction does not survive such\n"
"        relicensing or conveying.\n\n"
"        If you add terms to a covered work in accord with this section, you must place,  in\n"
"        the  relevant source files, a statement of the additional terms that apply to those\n"
"        files, or a notice indicating where to find the applicable terms.\n\n"
"        Additional terms, permissive or non-permissive, may be stated  in  the  form  of  a\n"
"        separately  written  license, or stated as exceptions; the above requirements apply\n"
"        either way.\n\n"
"    8. Termination.\n"
"        You may not propagate or modify a covered work except as expressly  provided  under\n"
"        this  License.   Any  attempt otherwise to propagate or modify it is void, and will\n"
"        automatically terminate your  rights  under  this  License  (including  any  patent\n"
"        licenses granted under the third paragraph of section 11).\n\n"
"        However,  if  you  cease  all  violation  of this License, then your license from a\n"
"        particular copyright holder is reinstated (a) provisionally, unless and  until  the\n"
"        copyright   holder   explicitly  and  finally  terminates  your  license,  and  (b)\n"
"        permanently, if the copyright holder fails to notify you of the violation  by  some\n"
"        reasonable means prior to 60 days after the cessation.\n\n"
"        Moreover, your license from a particular copyright holder is reinstated permanently\n"
"        if  the  copyright  holder  notifies you of the violation by some reasonable means,\n"
"        this is the first time you have received notice of violation of this  License  (for\n"
"        any  work)  from that copyright holder, and you cure the violation prior to 30 days\n"
"        after your receipt of the notice.\n\n"
"        Termination of your rights under this section does not terminate  the  licenses  of\n"
"        parties  who  have  received copies or rights from you under this License.  If your\n"
"        rights have been terminated and not permanently reinstated, you do not  qualify  to\n"
"        receive new licenses for the same material under section 10.\n\n"
"    9. Acceptance Not Required for Having Copies.\n"
"        You  are  not  required to accept this License in order to receive or run a copy of\n"
"        the Program.  Ancillary propagation  of  a  covered  work  occurring  solely  as  a\n"
"        consequence  of using peer-to-peer transmission to receive a copy likewise does not\n"
"        require acceptance.  However, nothing other than this License grants you permission\n"
"        to propagate or modify any covered work.  These actions infringe copyright  if  you\n"
"        do not accept this License.  Therefore, by modifying or propagating a covered work,\n"
"        you indicate your acceptance of this License to do so.\n\n"
"    10. Automatic Licensing of Downstream Recipients.\n"
"        Each time you convey a covered work, the recipient automatically receives a license\n"
"        from  the  original  licensors,  to run, modify and propagate that work, subject to\n"
"        this License.  You are not responsible for enforcing compliance  by  third  parties\n"
"        with this License.\n\n"
"        An  \"entity  transaction\" is a transaction transferring control of an organization,\n"
"        or substantially all assets of one, or  subdividing  an  organization,  or  merging\n"
"        organizations.    If   propagation  of  a  covered  work  results  from  an  entity\n"
"        transaction, each party to that transaction who receives a copy of  the  work  also\n"
"        receives  whatever  licenses to the work the party's predecessor in interest had or\n"
"        could give under the  previous  paragraph,  plus  a  right  to  possession  of  the\n"
"        Corresponding  Source  of  the  work  from  the  predecessor  in  interest,  if the\n"
"        predecessor has it or can get it with reasonable efforts.\n\n"
"        You may not impose any further restrictions on the exercise of the  rights  granted\n"
"        or  affirmed  under  this  License.  For example, you may not impose a license fee,\n"
"        royalty, or other charge for exercise of rights granted under this License, and you\n"
"        may not initiate litigation (including a cross-claim or counterclaim in a  lawsuit)\n"
"        alleging that any patent claim is infringed by making, using, selling, offering for\n"
"        sale, or importing the Program or any portion of it.\n\n"
"    11. Patents.\n"
"        A  \"contributor\" is a copyright holder who authorizes use under this License of the\n"
"        Program or a work on which the Program is based.  The work thus licensed is  called\n"
"        the contributor's \"contributor version\".\n\n"
"        A contributor's \"essential patent claims\" are all patent claims owned or controlled\n"
"        by  the  contributor, whether already acquired or hereafter acquired, that would be\n"
"        infringed by some manner, permitted by this License, of making, using,  or  selling\n"
"        its  contributor version, but do not include claims that would be infringed only as\n"
"        a consequence of further modification of the contributor version.  For purposes  of\n"
"        this  definition,  \"control\"  includes  the  right to grant patent sublicenses in a\n"
"        manner consistent with the requirements of this License.\n\n"
"        Each contributor grants you a non-exclusive, worldwide, royalty-free patent license\n"
"        under the contributor's essential patent claims, to  make,  use,  sell,  offer  for\n"
"        sale,  import  and  otherwise  run,  modify  and  propagate  the  contents  of  its\n"
"        contributor version.\n\n"
"        In the following three paragraphs, a \"patent license\" is any express  agreement  or\n"
"        commitment,  however  denominated,  not  to  enforce  a  patent (such as an express\n"
"        permission to practice a patent or covenant not to sue  for  patent  infringement).\n"
"        To  \"grant\"  such  a  patent  license to a party means to make such an agreement or\n"
"        commitment not to enforce a patent against the party.\n\n"
"        If you convey a covered work, knowingly  relying  on  a  patent  license,  and  the\n"
"        Corresponding  Source  of  the  work  is  not available for anyone to copy, free of\n"
"        charge and under the terms of this License, through a  publicly  available  network\n"
"        server  or  other  readily  accessible  means,  then  you must either (1) cause the\n"
"        Corresponding Source to be so available, or (2) arrange to deprive yourself of  the\n"
"        benefit of the patent license for this particular work, or (3) arrange, in a manner\n"
"        consistent  with  the requirements of this License, to extend the patent license to\n"
"        downstream recipients.  \"Knowingly relying\" means you have actual  knowledge  that,\n"
"        but  for  the patent license, your conveying the covered work in a country, or your\n"
"        recipient's use of the covered work in  a  country,  would  infringe  one  or  more\n"
"        identifiable patents in that country that you have reason to believe are valid.\n\n"
"        If,  pursuant  to  or  in  connection with a single transaction or arrangement, you\n"
"        convey, or propagate by procuring conveyance of, a covered work, and grant a patent\n"
"        license to some of the parties receiving the covered work authorizing them to  use,\n"
"        propagate,  modify  or  convey a specific copy of the covered work, then the patent\n"
"        license you grant is automatically extended to all recipients of the  covered  work\n"
"        and works based on it.\n\n"
"        A patent license is \"discriminatory\" if it does not include within the scope of its\n"
"        coverage,  prohibits  the exercise of, or is conditioned on the non-exercise of one\n"
"        or more of the rights that are specifically granted under this  License.   You  may\n"
"        not  convey  a covered work if you are a party to an arrangement with a third party\n"
"        that is in the business of distributing software, under which you make  payment  to\n"
"        the  third  party  based  on the extent of your activity of conveying the work, and\n"
"        under which the third party grants, to any of the parties  who  would  receive  the\n"
"        covered  work  from  you,  a  discriminatory  patent license (a) in connection with\n"
"        copies of the covered work conveyed by you (or copies made from those  copies),  or\n"
"        (b)  primarily  for  and  in connection with specific products or compilations that\n"
"        contain the covered work, unless you entered into that arrangement, or that  patent\n"
"        license was granted, prior to 28 March 2007.\n\n"
"        Nothing  in  this  License  shall be construed as excluding or limiting any implied\n"
"        license or other defenses to infringement that may otherwise be  available  to  you\n"
"        under applicable patent law.\n\n"
"    12. No Surrender of Others' Freedom.\n"
"        If  conditions  are imposed on you (whether by court order, agreement or otherwise)\n"
"        that contradict the conditions of this License, they do not  excuse  you  from  the\n"
"        conditions  of  this License.  If you cannot convey a covered work so as to satisfy\n"
"        simultaneously  your  obligations  under  this  License  and  any  other  pertinent\n"
"        obligations,  then  as a consequence you may not convey it at all.  For example, if\n"
"        you agree to terms that obligate you to collect a  royalty  for  further  conveying\n"
"        from  those  to  whom  you  convey the Program, the only way you could satisfy both\n"
"        those terms and this License would  be  to  refrain  entirely  from  conveying  the\n"
"        Program.\n\n"
"    13. Use with the GNU Affero General Public License.\n"
"        Notwithstanding any other provision of this License, you have permission to link or\n"
"        combine  any  covered  work  with a work licensed under version 3 of the GNU Affero\n"
"        General Public License into a single combined work, and  to  convey  the  resulting\n"
"        work.   The  terms  of this License will continue to apply to the part which is the\n"
"        covered work, but the  special  requirements  of  the  GNU  Affero  General  Public\n"
"        License,  section  13,  concerning  interaction through a network will apply to the\n"
"        combination as such.\n\n"
"    14. Revised Versions of this License.\n"
"        The Free Software Foundation may publish revised and/or new  versions  of  the  GNU\n"
"        General  Public  License  from  time to time.  Such new versions will be similar in\n"
"        spirit to the present version, but may differ in detail to address new problems  or\n"
"        concerns.\n\n"
"        Each  version  is  given a distinguishing version number.  If the Program specifies\n"
"        that a certain numbered version of the GNU General Public  License  \"or  any  later\n"
"        version\"  applies  to it, you have the option of following the terms and conditions\n"
"        either of that numbered version or of any  later  version  published  by  the  Free\n"
"        Software  Foundation.   If the Program does not specify a version number of the GNU\n"
"        General Public License, you may choose any  version  ever  published  by  the  Free\n"
"        Software Foundation.\n\n"
"        If  the  Program specifies that a proxy can decide which future versions of the GNU\n"
"        General Public License can be used, that proxy's public statement of acceptance  of\n"
"        a version permanently authorizes you to choose that version for the Program.\n\n"
"        Later  license versions may give you additional or different permissions.  However,\n"
"        no additional obligations are imposed on any author or copyright holder as a result\n"
"        of your choosing to follow a later version.\n\n"
"    15. Disclaimer of Warranty.\n"
"        THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED  BY  APPLICABLE  LAW.\n"
"        EXCEPT  WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES\n"
"        PROVIDE THE PROGRAM \"AS IS\" WITHOUT WARRANTY  OF  ANY  KIND,  EITHER  EXPRESSED  OR\n"
"        IMPLIED,  INCLUDING,  BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY\n"
"        AND FITNESS FOR A PARTICULAR PURPOSE.  THE  ENTIRE  RISK  AS  TO  THE  QUALITY  AND\n"
"        PERFORMANCE  OF  THE  PROGRAM IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU\n"
"        ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.\n\n"
"    16. Limitation of Liability.\n"
"        IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED  TO  IN  WRITING  WILL  ANY\n"
"        COPYRIGHT  HOLDER,  OR  ANY  OTHER PARTY WHO MODIFIES AND/OR CONVEYS THE PROGRAM AS\n"
"        PERMITTED ABOVE, BE LIABLE TO YOU FOR  DAMAGES,  INCLUDING  ANY  GENERAL,  SPECIAL,\n"
"        INCIDENTAL  OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE\n"
"        PROGRAM (INCLUDING BUT  NOT  LIMITED  TO  LOSS  OF  DATA  OR  DATA  BEING  RENDERED\n"
"        INACCURATE  OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM\n"
"        TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER  PARTY  HAS  BEEN\n"
"        ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.\n\n"
"    17. Interpretation of Sections 15 and 16.\n"
"        If  the disclaimer of warranty and limitation of liability provided above cannot be\n"
"        given local legal effect according to their terms,  reviewing  courts  shall  apply\n"
"        local  law that most closely approximates an absolute waiver of all civil liability\n"
"        in connection with the Program,  unless  a  warranty  or  assumption  of  liability\n"
"        accompanies a copy of the Program in return for a fee.\n\n"
"END OF TERMS AND CONDITIONS\n"
"How to Apply These Terms to Your New Programs\n"
"    If you develop a new program, and you want it to be of the greatest possible use to the\n"
"    public,  the  best  way  to achieve this is to make it free software which everyone can\n"
"    redistribute and change under these terms.\n\n"
"    To do so, attach the following notices to the program.  It is safest to attach them  to\n"
"    the  start of each source file to most effectively state the exclusion of warranty; and\n"
"    each file should have at least the \"copyright\" line and a pointer  to  where  the  full\n"
"    notice is found.\n\n"
"            <one line to give the program's name and a brief idea of what it does.>\n"
"            Copyright (C) <year> <name of author>\n\n"
"            This program is free software: you can redistribute it and/or modify\n"
"            it under the terms of the GNU General Public License as published by\n"
"            the Free Software Foundation, either version 3 of the License, or (at\n"
"            your option) any later version.\n\n"
"            This program is distributed in the hope that it will be useful, but\n"
"            WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU\n"
"            General Public License for more details.\n\n"
"            You should have received a copy of the GNU General Public License\n"
"            along with this program.  If not, see <https://www.gnu.org/licenses/>.\n\n"
"    Also add information on how to contact you by electronic and paper mail.\n\n"
"    If  the program does terminal interaction, make it output a short notice like this when\n"
"    it starts in an interactive mode:\n\n"
"            <program> Copyright (C) <year> <name of author>\n"
"            This program comes with ABSOLUTELY NO WARRANTY; for details type \"show w\".\n"
"            This is free software, and you are welcome to redistribute it\n"
"            under certain conditions; type \"show c\" for details.\n\n"
"    The hypothetical commands show w and show c should show the appropriate  parts  of  the\n"
"    General  Public  License.  Of course, your program's commands might be different; for a\n"
"    GUI interface, you would use an \"about box\".\n\n"
"    You should also get your employer (if you work as a programmer) or school, if  any,  to\n"
"    sign  a  \"copyright disclaimer\" for the program, if necessary.  For more information on\n"
"    this, and how to apply and follow the GNU GPL, see <https://www.gnu.org/licenses/>.\n\n"
"    The GNU General  Public  License  does  not  permit  incorporating  your  program  into\n"
"    proprietary  programs.   If  your  program is a subroutine library, you may consider it\n"
"    more useful to permit linking proprietary applications with the library.   If  this  is\n"
"    what you want to do, use the GNU Lesser General Public License instead of this License. \n"
"    But first, please read <https://www.gnu.org/licenses/why-not-lgpl.html>.                \n";


/*
*   ORDER OF FORMATS:
*       name desc snv year author
*/

#define GPLGENFP(fp, ct, name, desc, snv, year, author)\
    fprintf(fp, GPL_COMMENT_FORMAT_STRING, GPL_COMMENT_STARTS[ct],\
    GPL_COMMENT_CONTINUES[ct], name, desc, snv,\
    GPL_COMMENT_CONTINUES[ct], year, author,\
    GPL_COMMENT_CONTINUES[ct], GPL_COMMENT_CONTINUES[ct],\
    GPL_COMMENT_CONTINUES[ct], GPL_COMMENT_CONTINUES[ct],\
    GPL_COMMENT_CONTINUES[ct], GPL_COMMENT_CONTINUES[ct],\
    GPL_COMMENT_CONTINUES[ct], GPL_COMMENT_CONTINUES[ct],\
    GPL_COMMENT_CONTINUES[ct], GPL_COMMENT_CONTINUES[ct],\
    GPL_COMMENT_ENDS[ct]);

static const char *GPL_COMMENT_FORMAT_STRING =
"%s\n"
"%s   %s, %s %s\n"
"%s   Copyright (C) %s %s\n"
"%s            This program is free software: you can redistribute it and/or modify\n"
"%s            it under the terms of the GNU General Public License as published by\n"
"%s            the Free Software Foundation, either version 3 of the License, or (at\n"
"%s            your option) any later version.\n"
"%s            This program is distributed in the hope that it will be useful, but\n"
"%s            WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"%s            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU\n"
"%s            General Public License for more details.\n"
"%s            You should have received a copy of the GNU General Public License\n"
"%s            along with this program.  If not, see <https://www.gnu.org/licenses/>.\n"
"%s\n";

enum GPL_COMMENT_TYPE {
    CM_C,
    CM_CXX,
    CM_PYTHON,
    CM_VISUAL_BASIC,
    CM_OCAML,
    CM__MAX
};

static const char *GPL_COMMENT_TYPE_REP[CM__MAX] = {
    "C", "C++", "Python", "VBasic", "Ocaml"
};

static const char *GPL_COMMENT_STARTS[CM__MAX] = {
    "/*",
    "//",
    "#",
    "'",
    "(*"
};
static const char *GPL_COMMENT_ENDS[CM__MAX] = {
    "*/",
    "//",
    "#",
    "'",
    "*)"
};
static const char *GPL_COMMENT_CONTINUES[CM__MAX] = {
    "*",
    "//",
    "#",
    "'",
    "*"
};


#endif




